### ISSUE TITLE
Incorrect call to addSubscriber in Observer

### ISSUE THREAD

**Issue by AndreKlang** [karlssonlord/rulemailer#12]
[On this line](https://github.com/rulecom/rulemailer/blob/master/src/app/code/community/KL/Rulemailer/Model/Observer.php#L60) is a call to ```$this->addSubscriber()``` with totaly wrong set of parameters.

Parameters given is (String, Array, Array, Boolean, Boolean, Boolean).

Expected parameters is (Mage_Customer_Model_Customer, Array, Array)

This cause a fatal error whenever the event ```cart_save_after_handler``` is fired for a logged in customer.

The issues caused by this is probably very different from store to store, in our case it has caused a lot of customers to get incorrect invoices where the discounts is missing.

**Comment by swesam** [comment]
Hi Andre! 
Thanks for sharing this, we are working on a fix.

**Comment by AndreKlang** [comment]
Hey, Just looked it over, it's better, but it is still wrong.

The call has six parameters, the method only accepts three.

I can highly recommend that you use an IDE like Phpstorm, and make sure that you have everything documented with phpDoc, you would see these kinds of issues with ease.

**Comment by athe0i** [comment]
Hello. 
Thank you for pointing that out. I'll double check the plugin for other mistakes. 
About your suggestion:
> I can highly recommend that you use an IDE like Phpstorm, and make sure that you have everything documented with phpDoc, you would see these kinds of issues with ease.

PHPStorm actually didn`t highlight anything about that call, so that reminds us to not rely on the IDEs.
