### ISSUE TITLE
No multistore support

### ISSUE THREAD

**Issue by AndreKlang** [karlssonlord/rulemailer#8]
It is not possible to use this with multiple stores and/or multiple API-keys.

It does work as expected in frontend, but only in frontend. Any API-calls made from backend will use the API-key set in global scope, not the correct corresponding scope for the current entity.

Also, there is no way to disable the module per store. As long as the module is installed it will try to export all orders, regardless if there is an API-key or not.

The reason it works in frontend is because `Mage::getStoreConfig('p/a/th')` uses the current loaded scope to get config. Which is fine in frontend, but in backend that scope is "Admin" (id 0). To get the correct config for another scope one need to specify it, like so: `Mage::getStoreConfig('p/a/th', $order->getStore()->getId())` (Example for an order)

**Comment by athe0i** [comment]
Hello. 

Just checked on some simple local examples and seems it does using corresponding api keys(both for new subscription and order mails). 
Please, describe if possible your use case(may be installation too) more concrete so we can reproduce it.

Regarding multiple store enabling issue for that had been created.

Regards,
Stan

**Comment by AndreKlang** [comment]
The specific problem I had was with the cron-job, going through all past orders.
With that in mind I checked where & how the API-key is fetched from config, and the one place I did find (maybe there is more than one place?) did not specify scope. Making it impossible to work anywhere other then frontend.

A good way to test this is to leave the API-key field empty in global scope, and only fill it out in store scope. That way you will easily see what is working and what is not.

**Comment by athe0i** [comment]
hm... okay, seems i've discovered the simple solution. so while you are setting the api key on store view level it does work, but while you are setting it on website level it does not. so the fast fix for you should work setting keys per view(if sure you have not too much of them). we'll fix website level config soon.

thanks for reporting the issue.
